[project]
name = "test-mcp"
version = "0.1.0"
description = "MCP server test"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.9.4",
    "requests>=2.32.4",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
